source 'https://rubygems.org'

ruby '2.2.2'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
gem 'mysql2'
gem 'rest-client'
gem 'json'
gem 'elasticsearch'
gem 'colorize'